export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_FAILED = "PRODUCTS_FAILED";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const PROMOTIONS_LOADING = "PROMOTIONS_LOADING";
export const ADD_PROMOTIONS = "ADD_PROMOTIONS";
export const PROMOTIONS_FAILED = "PROMOTIONS_FAILED";